apiVersion: apps/v1
kind: Deployment 
metadata:
 name: java-ms
 labels:
   app: java-ms
spec:
  replicas: 2
  selector:
   matchLabels: 
     app: java-ms
  template:
    metadata:
      labels:
        app: java-ms 
    spec: 
     containers:
     - name: java-ms 
       image: ankit1111/account-service
       ports: 
       - containerPort: 2222
         protocol: TCP
     imagePullSecrets:
     - name: java   
---
apiVersion: v1
kind: Service
metadata:
 name: java-ms-services
 labels:
   app: java-ms
        
spec:
 type: NodePort
 ports:
  - port: 2222
    targetPort: 2222
    nodePort: 30003
 selector:
    app: java-ms
