apiVersion: v1
kind: Service
metadata:
 name: nginxservices
 labels:
   app: nginx
        
spec:
 type: NodePort
 ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
 selector:
    app: nginx
