apiVersion: v1
kind: PersistentVolume 
metadata:
  name: pv-nginx
spec:
 storageClassName: manual 
 capacity:
   storage: 4G
 accessModes: 
  - ReadWriteOnce  
 hostPath:
   path: "/opt/backup"
root@ip-172-31-7-109:~# cat pvc.yaml 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nginx
spec:
 storageClassName: manual
 accessModes: 
   - ReadWriteOnce
 resources:
   requests:
    storage: 2Gi
